# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_newsinfo_website_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsinfo',
            name='website_url',
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
